// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfyuwmpvhokdiyqcjgyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmeXV3bXB2aG9rZGl5cWNqZ3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzQzOTksImV4cCI6MjA2OTUxMDM5OX0.QPTGnNr3bswCO-kT_fFQPZkQcO4OvP-llsZ5apztAI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});